[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
	repo = 'scrooloose/nerdtree'
	hook_add='''
	let g:NERDTreeShowBookmarks=1
	autocmd StdinReadPre * let s:std_in=1
	autocmd vimenter * if argc() == 0 && !exists("s:std_in") |NERDTree|endif
	'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cespare/vim-toml'


[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'kassio/neoterm'


[[plugins]]
repo = 'itchyny/lightline.vim'


[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'scrooloose/nerdtree'
